version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - pip install awscli --upgrade
      - npm install
  build:
    commands:
      - npm run build > output.log
      - cp output.log _output
      - aws s3 rm $COLLECTIONS_BROWSER_S3_BUCKET --recursive
      - aws s3 sync _output/ $COLLECTIONS_BROWSER_S3_BUCKET --delete --acl=bucket-owner-full-control
